version: "3"
services:

  jupyter:
    build:
      context: ./
    ports:
      - "8888:8888"
    volumes:
          - "./src:/modeling/src" 
          - "./test:/modeling/test"
          - "./data:/data"
    environment:
      JUPYTER_ENABLE_LAB: "yes"

  postgresDb:
    image: postgres:latest
    restart: 'no'
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
      POSTGRES_DB: studentdb